wiki_page:
  page_id: "1436811681"
  page_title: "Test Data Insights (Android & iOS)"
  sections:
    - name: "UI Test Data Insights - Android"
      reports:
        - report-title: "Fenix UI Test Health Index"
          report-description: "A holistic, categorical score to summarize test health at a glance."
          attachment-filename: "fenix-ui-test-health-index.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2901"
          approval-status: "informational"
        - report-title: "Focus UI Test Health Index"
          report-description: "A holistic, categorical score to summarize test health at a glance."
          attachment-filename: "focus-ui-test-health-index.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2902"
          approval-status: "informational"
        - report-title: "Fenix UI Test Flaky Rate KPI (Current Month Average)"
          report-description: "The average percentage of flaky tests in the last 30 days."
          attachment-filename: "fenix-ui-test-flaky-rate-kpi-cur-month-avg.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2898"
          approval-status: "approved"
        - report-title: "Focus UI Test Flaky Rate KPI (Current Month Average)"
          report-description: "The average percentage of flaky tests in the last 30 days."
          attachment-filename: "focus-ui-test-flaky-rate-kpi-cur-month-avg.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2900"
          approval-status: "approved"
        - report-title: "Fenix UI Test Failure Rate KPI (Current Month Average)"
          report-description: "The average percentage of failed tests in the last 30 days."
          attachment-filename: "fenix-ui-test-failure-rate-kpi-cur-month-avg.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2903"
          approval-status: "approved"
        - report-title: "Focus UI Test Failure Rate KPI (Current Month Average)"
          report-description: "The average percentage of failed tests in the last 30 days."
          attachment-filename: "focus-ui-test-failure-rate-kpi-cur-month-avg.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2906"
          approval-status: "approved"
        - report-title: "Fenix UI Test Flaky Rate KPI (Month over Month)"
          report-description: "The percentage of flaky tests in the last 30 days compared to the previous 30 days."
          attachment-filename: "fenix-ui-test-flaky-rate-month-over-month-kpi.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2835"
          approval-status: "approved"
        - report-title: "Focus UI Test Flaky Rate KPI (Month over Month)"
          report-description: "The percentage of flaky tests in the last 30 days compared to the previous 30 days."
          attachment-filename: "focus-ui-test-flaky-rate-month-over-month-kpi.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2839"
          approval-status: "approved"
        - report-title: "Fenix UI Test Failure Rate KPI (Month over Month)"
          report-description: "The percentage of failed tests in the last 30 days compared to the previous 30 days."
          attachment-filename: "fenix-ui-test-failure-rate-month-over-month-kpi.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2837"
          approval-status: "approved"
        - report-title: "Focus UI Test Failure Rate KPI (Month over Month)"
          report-description: "The percentage of failed tests in the last 30 days compared to the previous 30 days."
          attachment-filename: "focus-ui-test-failure-rate-month-over-month-kpi.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2907"
          approval-status: "approved"
        - report-title: "Fenix UI Test Flaky Rate by Month"
          report-description: "The percentage of flaky tests by month."
          attachment-filename: "fenix-ui-test-flaky-rate-by-month.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2869"
          approval-status: "approved"
        - report-title: "Fenix UI Test Failure Rate by Month"
          report-description: "The percentage of failed tests by month."
          attachment-filename: "fenix-ui-test-failure-rate-by-month.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2871"
          approval-status: "approved"
        - report-title: "Fenix UI Test Monthly Run Volume of UI Tests"
          report-description: "The number of tests run by month across all jobs."
          attachment-filename: "fenix-ui-test-monthly-run-volume.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2891"
          approval-status: "pending"
        - report-title: "Focus UI Test Monthly Run Volume of UI Tests"
          report-description: "The number of tests run by month across all jobs."
          attachment-filename: "focus-ui-test-monthly-run-volume.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2893"
          approval-status: "pending"

    - name: "UI Test Data Insights - iOS"
      reports:
        - report-title: "Firefox iOS Test Health Index"
          report-description: "A holistic, categorical score to summarize test health at a glance."
          attachment-filename: "fennec-ui-test-health-index.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2931"
          approval-status: "informational"
        - report-title: "Firefox iOS Flaky Rate KPI"
          report-description: "Firefox iOS Flaky Rate KPI (Current Month Average)"
          attachment-filename: "fennec-flaky-rate-kpi.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2928"
          approval-status: "approved"
        - report-title: "Fennec Failure Rate KPI"
          report-description: "Firefox iOS UI Test Failure Rate KPI (Current Month Average)"
          attachment-filename: "fennec-failure-rate-kpi.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2929"
          approval-status: "approved"
        - report-title: "Fennec UI Test Flaky Rate KPI (Month over Month)"
          report-description: "The percentage of flaky tests in the last 30 days compared to the previous 30 days."
          attachment-filename: "fennec-runs-change-kpi.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2930"
          approval-status: "informational"
        - report-title: "Fennec UI Test Flaky Rate KPI (Month over Month)"
          report-description: "The percentage of flaky tests in the last 30 days compared to the previous 30 days."
          attachment-filename: "fennec-flaky-rate-kpi-status.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2932"
          approval-status: "informational"
        - report-title: "Fennec UI Test Failure Rate KPI (Month over Month)"
          report-description: "The percentage of failed tests in the last 30 days compared to the previous 30 days."
          attachment-filename: "fennec-failure-rate-kpi-status.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/2933"
          approval-status: "informational"
        - report-title: "Fennec UI Flaky Tests Trend"
          report-description: "Firefox iOS UI Flaky Tests Trend in 2025"
          attachment-filename: "fennec-number-of-flaky-tests-trend.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2888"
          approval-status: "informational"
        - report-title: "Fennec UI Failure Tests Trend"
          report-description: "Firefox iOS UI Failure Tests Trend in 2025"
          attachment-filename: "fennec-number-of-failure-tests-trend.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2889"
          approval-status: "informational"
        - report-title: "Fennec Firefox iOS - Flaky Rate By Day"
          report-description: "Fennec Firefox iOS - Flaky Rate By Day 2025"
          attachment-filename: "fennec-ui-tests-flaky-rate-by-day-iphone.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2851"
          approval-status: "approved"
        - report-title: "Fennec Firefox iOS - Failure Rate By Day"
          report-description: "Fennec Firefox iOS - Failure Rate By Day 2025"
          attachment-filename: "fennec-firefox-ios-failure-rate-by-day-iphone.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2852"
          approval-status: "approved"
        - report-title: "Fennec Firefox iOS Daily Run Volume of UI Tests All Jobs - iPhone"
          report-description: "Fennec Firefox iOS Daily Run Volume of UI Tests All Jobs - iPhone"
          attachment-filename: "fennec-firefox-ios-daily-run-volume-of-ui-tests-all-jobs-iphone.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2855"
          approval-status: "approved"
        - report-title: "Fennec Firefox iOS Monthly Run Volume of UI Tests All Jobs - iPhone"
          report-description: "Fennec Firefox iOS Monthly Run Volume of UI Tests All Jobs - iPhone"
          attachment-filename: "fennec-firefox-ios-monthly-run-volume-of-ui-tests-all-jobs-iphone.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2857"
          approval-status: "approved"
        - report-title: "Fennec Firefox iOS - Flaky Rate By Day"
          report-description: "Fennec Firefox iOS - Flaky Rate By Day 2025"
          attachment-filename: "fennec-ui-tests-flaky-rate-by-day-ipad.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2853"
          approval-status: "approved"
        - report-title: "Firefox iOS Monthly Failure Rate By Month of UI Tests - iPhone"
          report-description: "The percentage of failure tests by month for iPhone."
          attachment-filename: "fennec-ui-tests-failure-rate-by-month-iphone.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2984"
          approval-status: "approved"
        - report-title: "Firefox iOS Monthly Failure Rate of UI Tests - iPad"
          report-description: "The percentage of failure tests by month for iPad."
          attachment-filename: "fennec-ui-tests-failure-rate-by-month-ipad.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2983"
          approval-status: "approved"
        - report-title: "Firefox iOS Monthly Flaky Rate of UI Tests - iPhone"
          report-description: "The percentage of flaky tests by month for iPhone."
          attachment-filename: "fennec-ui-tests-flaky-rate-by-month-iphone.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2985"
          approval-status: "approved"
        - report-title: "Fennec Firefox iOS Monthly Flaky Rate of UI Tests - iPad"
          report-description: "The percentage of flaky tests by month for iPad."
          attachment-filename: "fennec-ui-tests-flaky-rate-by-month-ipad.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2986"
          approval-status: "approved"
        - report-title: "Fennec Firefox iOS Monthly Run Volume of UI Tests All Jobs - iPad"
          report-description: "Fennec Firefox iOS Monthly Run Volume of UI Tests All Jobs - iPad"
          attachment-filename: "fennec-firefox-ios-monthly-run-volume-of-ui-tests-all-jobs-ipad.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2858"
          approval-status: "approved"
        - report-title: "Fennec Monthly Run Volume of UI Tests"
          report-description: "Firefox iOS Monthly Run Volume of UI Tests"
          attachment-filename: "fennec-firefox-ios-monthly-run-volume-of-ui-tests.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2872"
          approval-status: "approved"
        - report-title: "Fennec Firefox iOS Failure Rate By Month of UI Tests"
          report-description: "Firefox iOS Failure Rate By Month of UI Tests"
          attachment-filename: "fennec-firefox-ios-failure-rate-by-month-of-ui-tests.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/embed/looks/2873"
          approval-status: "approved"
