wiki_page:
  page_id: 1631911951
  page_title: "iOS Health Monitor Report"
  show_approval_status: false
  sections:
    - name: "Sentry"
      reports:
        - report-title: "Crash Free Users Rate"
          report-description: "Crash Free Users Rate"
          attachment-filename: "firefox-ios-crash-free-rate-user.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3122"
        - report-title: "Crash Free Session Rate"
          report-description: "Crash Free Session Rate"
          attachment-filename: "firefox-ios-crash-free-rate-session.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3123"
        - report-title: "Adoption Rate"
          report-description: "Adoption Rate"
          attachment-filename: "firefox-ios-adoption-rate.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3124"