wiki_page:
  page_id: 2208628737
  page_title: "Team Delivery Insights 2026"
  show_approval_status: false
  sections:
    - name: "Testing"
      reports:
        - report-title: "Workload Per Platform 2026"
          report-description: "Number of Feature Requests Per Platform in 2026"
          attachment-filename: "workload-per-platform-2026.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3199"
        - report-title: "Firefox iOS Verified Builds 2026"
          report-description: "Number of Firefox iOS Verified Builds in 2026"
          attachment-filename: "firefox-ios-verified-builds-pie-chart-2026.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3204"
        - report-title: "Firefox for Android Verified Builds 2026"
          report-description: "Number of Firefox for Android Verified Builds in 2026"
          attachment-filename: "fenix-verified-builds-pie-chart-2026.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3205"
        - report-title: "Firefox iOS Verified Builds 2026 (Column Chart)"
          report-description: "Number of Firefox iOS Verified Builds in 2026 (Column Chart)"
          attachment-filename: "firefox-ios-verified-builds-column-chart-2026.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3206"
        - report-title: "Firefox for Android Verified Builds 2026 (Column Chart)"
          report-description: "Number of Firefox for Android Verified Builds in 2026 (Column Chart)"
          attachment-filename: "fenix-verified-builds-column-chart-2026.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3207"
        - report-title: "Focus for Android Verified Builds 2026 (Column Chart)"
          report-description: "Number of Focus for Android Verified Builds in 2026"
          attachment-filename: "focus-android-verified-builds-column-chart-2026.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3208"
        - report-title: "Focus for iOS Verified Builds 2026 (Column Chart)"
          report-description: "Number of Focus for iOS Verified Builds in 2026"
          attachment-filename: "focus-ios-verified-builds-column-chart-2026.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3209"
      
    - name: "Incidents"
      reports:
        - report-title: "Mobile Incidents by Platform 2026"
          report-description: "Number of Incidents by Platform in 2026"
          attachment-filename: "mobile-incidents-2026-pie-chart.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3202"
        - report-title: "Mobile Incidents by Month - 2026"
          report-description: "Mobile Incidents by Month in 2026"
          attachment-filename: "mobile-incidents-month-2026.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3203"