wiki_page:
  page_id: 2019819530
  page_title: "DTE - Manual Bugzilla Metrics Insights"
  show_approval_status: false
  sections:
    - name: "Defect Counts"
      reports:
        - report-title: "Total new defects reported"
          report-description: "Displays the total number of valid defects reported by our team across releases."
          attachment-filename: "total-new-defects-reported.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3140"
        - report-title: "Total new S1/S2 defects reported"
          report-description: "Represents the total number of newly logged S1 and S2 severity issues identified by the team for each release cycle."
          attachment-filename: "total-new-s1s2-defects-reported.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3142"
        - report-title: "Total new regression defects reported"
          report-description: "Indicates the total number of newly logged regression bugs, where previously working functionality has broken in the current release."
          attachment-filename: "total-new-regression-defects-reported.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3141"
        - report-title: "Total new defects reported by channel"
          report-description: "Shows the total number of new defects logged by the team, categorized by release channel (Nightly vs Beta)"
          attachment-filename: "total-new-defects-reported-by-channel.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3143"

    - name: "Fixed and Deferred Bugs"
      reports:
        - report-title: "Average time-to-fix in workdays"
          report-description: "Represents the average number of working days required for defects reported by the team to be resolved by engineering team."
          attachment-filename: "average-time-to-fix-in-workdays.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3146"
        - report-title: "Bugs fixed by release day"
          report-description: "Shows the total number of defects reported by our team that were successfully resolved before the release date."
          attachment-filename: "fixed-by-release-date.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3144"
        - report-title: "Bugs deferred (open by release day)"
          report-description: "Indicates the number of reported defects (excluding enhancements) that remained open or unresolved by the release date and were therefore deferred to future cycles."
          attachment-filename: "deferred-bug-open-by-release-day-with-enhancements-excluded.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3145"

    - name: "Overview of new regression defects reported"
      reports:
        - report-title: "Regression Bugs Fixed by Release Date"
          report-description: "Represents the total number of regression reported by our team that were resolved by the end of the release."
          attachment-filename: "regression-bugs-fixed-by-release-date.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3147"
        - report-title: "Deferred regression defects"
          report-description: "Shows the total regression defects still open or unresolved by the release date and were therefore deferred to future cycles."
          attachment-filename: "deferred-regression-defects.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3149"
        - report-title: "Regressions average time-to-fix in net workdays"
          report-description: "Shows the average time, in net workdays, taken to fix regression defects logged by our team during the release."
          attachment-filename: "regressions-average-time-to-fix-in-net-workdays.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3148"

    - name: "Overview of Bug Work Progress"
      reports:
        - report-title: "Bug fixes verified (done, or attempted)"
          report-description: "Total bug fixes verified by DTE (or attempted), broken down by release cycle."
          attachment-filename: "qa-ver-doneblocked-overall-bugs.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3150"
        - report-title: "Bugs investigated by Release Cycle"
          report-description: "Total bugs investigated by DTE, broken down by release cycle."
          attachment-filename: "qa-investig-overall-bugs.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3151"
        - report-title: "Bug Fixes Triaged Per Release Cycle"
          report-description: "Total bug fixes triaged by DTE for manual testing."
          attachment-filename: "qa-triage-overall-bugs.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3152"