wiki_page:
  page_id: 2019819530
  page_title: "DTE - Manual Bugzilla Metrics Insights"
  show_approval_status: false
  sections:
    - name: "Defect Counts"
      reports:
        - report-title: "Total new defects reported"
          report-description: "[DRAFT]"
          attachment-filename: ".png"
          looker-graph-url: ""
        - report-title: "Total new S1/S2 defects reported"
          report-description: "[DRAFT]"
          attachment-filename: ".png"
          looker-graph-url: ""
        - report-title: "Total new regression defects reported"
          report-description: "[DRAFT]"
          attachment-filename: ".png"
          looker-graph-url: ""
        - report-title: "Total new defects reported by channel"
          report-description: "[DRAFT]"
          attachment-filename: ".png"
          looker-graph-url: ""

    - name: "Release and Regression Metrics"
      reports:
        - report-title: "Number of Bugs per Release - Line"
          report-description: "[DRAFT]"
          attachment-filename: ".png"
          looker-graph-url: ""
        - report-title: "Fixed by release day"
          report-description: "[DRAFT]"
          attachment-filename: ".png"
          looker-graph-url: ""
        - report-title: "Deferred - open by release day (enhancements excluded)"
          report-description: "[DRAFT]"
          attachment-filename: ".png"
          looker-graph-url: ""
        - report-title: "Regressions fixed by release day"
          report-description: "[DRAFT]"
          attachment-filename: ".png"
          looker-graph-url: ""
        - report-title: "Overview of new deferred defects S1/S2"
          report-description: "[DRAFT]"
          attachment-filename: ".png"
          looker-graph-url: ""

    - name: "Bug Work Progress"
      reports:
        - report-title: "Overall Bug Work - Total Bugs Verified"
          report-description: "[DRAFT]"
          attachment-filename: ".png"
          looker-graph-url: ""
        - report-title: "WIP- Overall Bug Work - Total Bugs Uplifted Last"
          report-description: "[DRAFT]"
          attachment-filename: ".png"
          looker-graph-url: ""
        - report-title: "Overall Bug Work - Total Bugs Investigated"
          report-description: "[DRAFT]"
          attachment-filename: ".png"
          looker-graph-url: ""
        - report-title: "WIP - Overall Bug Work - Total Bugs Triaged"
          report-description: "[DRAFT]"
          attachment-filename: ".png"
          looker-graph-url: ""

    - name: "Time-to-Fix Metrics"
      reports:
        - report-title: "Average time-to-fix [net workdays]"
          report-description: "[DRAFT]"
          attachment-filename: ".png"
          looker-graph-url: ""
