wiki_page:
  page_id: 2019819530
  page_title: "DTE - Manual Bugzilla Metrics Insights"
  show_approval_status: false
  sections:
    - name: "Defect Counts"
      reports:
        - report-title: "Total new defects reported"
          report-description: "[DRAFT]"
          attachment-filename: "total_new_defects_reported.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3140"
        - report-title: "Total new S1/S2 defects reported"
          report-description: "[DRAFT]"
          attachment-filename: "total_new_s1s2_defects_reported.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3142"
        - report-title: "Total new regression defects reported"
          report-description: "[DRAFT]"
          attachment-filename: "total_new_regression_defects_reported.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3141"
        - report-title: "Total new defects reported by channel"
          report-description: "[DRAFT]"
          attachment-filename: "total_new_defects_reported_by_channel.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3143"

    - name: "Fixed and Deferred Bugs"
      reports:
        - report-title: "Average time-to-fix in workdays"
          report-description: "[DRAFT]"
          attachment-filename: "average_time_to_fix_in_workdays.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3146"
        - report-title: "Bugs fixed by release day"
          report-description: "[DRAFT]"
          attachment-filename: "fixed_by_release_date.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3144"
        - report-title: "Bugs deferred (open by release day)"
          report-description: "[DRAFT] (enhancements excluded)"
          attachment-filename: "deferred_bug_open_by_release_day_with_enhancements_excluded.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3145"

    - name: "Overview of new regression defects reported"
      reports:
        - report-title: "Regression Bugs Fixed by Release Date"
          report-description: "[DRAFT]"
          attachment-filename: "regression-bugs-fixed-by-release-date.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3147"
        - report-title: "Deferred regression defects"
          report-description: "[DRAFT]"
          attachment-filename: "deferred-regression-defects.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3149"
        - report-title: "Regressions average time-to-fix in net workdays"
          report-description: "[DRAFT]"
          attachment-filename: "regressions-average-time-to-fix-in-net-workdays.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3148"

    - name: "Overview of Bug Work Progress"
      reports:
        - report-title: "Overall Bugs Marks as Done/Blocked Per Release Cycle"
          report-description: "[DRAFT]"
          attachment-filename: "qa-ver-done/blocked-overall-bugs.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3150"
        - report-title: "Bugs investigated by Release Cycle"
          report-description: "[DRAFT]"
          attachment-filename: "qa-investig-overall-bugs.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3151"
        - report-title: "Total Bugs Triaged Per Release Cycle"
          report-description: "[DRAFT]"
          attachment-filename: "qa-triage-overall-bugs.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3152"