wiki_page:
  page_id: 1940062209
  page_title: "DTE Automated Desktop Metrics"
  sections:
    - name: "Automated Desktop Smoke Metrics"
      reports:
        - report-title: "Test Plan Counts"
          report-description: "Passed, Failed, Retested and Blocked Counts of each testcase in a test plan in the past month."
          attachment-filename: "test-plan-counts.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3096"
        - report-title: "Test Plans Frequency"
          report-description: "Number of test plans created in the past month grouped weekly."
          attachment-filename: "test-plans-frequency.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3044"
        - report-title: "Test Plans Ratio"
          report-description: "Percent Ratio of Passed, Blocked, Failed, Retested Test Cases in a test plan in the past month."
          attachment-filename: "test-plans-ratio.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3098"
        - report-title: "Test Plans Untested Count"
          report-description: "Untested Test Cases in a test plan in the past month."
          attachment-filename: "test-plans-untested-count.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3099"
        - report-title: "Desktop - Top 5 Longest Tests"
          report-description: "The 5 longest running tests."
          attachment-filename: "desktop-top-5-longest-tests.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3101"
        - report-title: "Test Runs Frequency"
          report-description: "Number of test runs created in the past month grouped weekly."
          attachment-filename: "test-runs-frequency.png"
          looker-graph-url: "https://mozilla.cloud.looker.com/looks/3100"
