name: Desktop Testops Report WEEKLY - Staging

# Monday @8am CET
on:
  schedule:
    - cron:  "0 8 * * 1"
  workflow_dispatch:

jobs:
  deploy:
    name: Desktop TestOps Report (WEEKLY) - Production
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v5

      - name: Setup python 
        uses: actions/setup-python@v6

      - name: Establish Cloud SQL Proxy
        uses: mattes/gce-cloudsql-proxy-action@v1
        with:
          creds: ${{ secrets.GCLOUD_AUTH }}
          instance: ${{ secrets.CLOUD_SQL_CONNECTION_NAME }}
          port: ${{ secrets.CLOUD_SQL_DATABASE_PORT }}

      - name: Install requirements 
        run: pip install -r requirements.txt

      - name: Set env vars 
        run: |
            echo "CLOUD_SQL_DATABASE_USERNAME=${{ secrets.CLOUD_SQL_DATABASE_USERNAME }}" >> $GITHUB_ENV
            echo "CLOUD_SQL_DATABASE_PASSWORD=${{ secrets.CLOUD_SQL_DATABASE_PASSWORD }}" >> $GITHUB_ENV
            echo "CLOUD_SQL_DATABASE_NAME=staging" >> $GITHUB_ENV
            echo "CLOUD_SQL_DATABASE_PORT=${{ secrets.CLOUD_SQL_DATABASE_PORT }}" >> $GITHUB_ENV
            echo "TESTRAIL_HOST=${{ secrets.TESTRAIL_HOST }}" >> $GITHUB_ENV
            echo "TESTRAIL_USERNAME=${{ secrets.TESTRAIL_USERNAME }}" >> $GITHUB_ENV
            echo "TESTRAIL_PASSWORD=${{ secrets.TESTRAIL_PASSWORD }}" >> $GITHUB_ENV
            echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
            echo "ATLASSIAN_API_TOKEN=${{ secrets.ATLASSIAN_API_TOKEN }}" >> $GITHUB_ENV
            echo "ATLASSIAN_HOST=${{ secrets.ATLASSIAN_HOST }}" >> $GITHUB_ENV
            echo "ATLASSIAN_USERNAME=${{ secrets.ATLASSIAN_USERNAME }}" >> $GITHUB_ENV

      - name: Query Test Plans and Runs
        run: python ./__main__.py --report-type testrail-test-results --project firefox-desktop
        continue-on-error: true

      - name: Query Bugzilla Release Flags Bugs
        run: python ./__main__.py --report-type bugzilla-desktop-release-flags-for-bugs
        continue-on-error: true

      - name: Query Bugzilla Overall Bugs
        run: python ./__main__.py --report-type bugzilla-desktop-overall-bugs
